name: CI Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Restore node_modules cache
        id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-node-

      # Install if cache was not found. (You can remove the if-statement
      # and always install if you want to ensure lockfile is fully respected.)
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

  prettier:
    name: Run Prettier
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Restore node_modules cache
        id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Run Prettier
        run: pnpm format --check

  tsc:
    name: TypeScript Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Restore node_modules cache
        id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Run TypeScript Check
        run: pnpm tsc
